version: '3.3'

services:
  web:
    build: ./project
    restart: on-failure
    command: gunicorn core.wsgi:application --reload --bind 0.0.0.0:1337 --workers 3
    volumes:
      - ./project/:/project/
      - ./project/static/:/static
    ports:
      - 1337:1337
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=*
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
    networks:
      - internal

  celery:
    build: ./project
    restart: on-failure
    command: celery --app=core worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project/:/project/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
    networks:
      - internal

  celery-beat:
    build: ./project
    restart: on-failure
    command: celery -A core beat -l info
    volumes:
      - ./project/:/project/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
    networks:
      - internal

  redis:
    image: redis:7-alpine
    restart: on-failure
    networks:
      - internal

  db:
    image: postgres
    restart: on-failure
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal

  dashboard:
    build: ./project
    restart: on-failure
    command: celery flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - celery
    networks:
      - internal

  nginx:
    build: ./nginx/local
    restart: on-failure
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - internal
    volumes:
      - ./project/:/project/
      - ./project/static/:/static
    depends_on:
      - web

volumes:
  dbdata:
  static:

networks:
  internal: