# Generated by Django 4.1.4 on 2023-06-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_commands_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=32),
        ),
    ]
