# Generated by Django 4.1.4 on 2023-06-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_telegramuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='order_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='payment_status',
            field=models.CharField(choices=[('NONE', 'NONE'), ('NEW', 'NEW'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED'), ('REFUNDED', 'REFUNDED')], default='NONE', max_length=15),
        ),
    ]
