# Generated by Django 4.1.4 on 2023-06-02 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_telegramuser_order_id_telegramuser_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='order_id',
            field=models.CharField(default=uuid.UUID('94837b55-805c-48f0-ac86-a5af72589cac'), max_length=36, unique=True),
        ),
    ]
