# Generated by Django 4.1.4 on 2023-06-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_alter_telegramuser_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='payment_status',
        ),
    ]
