# Generated by Django 4.1.4 on 2023-06-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_telegramuser_phone'),
        ('telegram_bot', '0007_remove_telegramuser_order_id_and_more'),
    ]

    operations = [
    ]
