# Generated by Django 4.1.4 on 2023-06-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_merge_20230603_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='order_id',
            field=models.CharField(default=None, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
