# Generated by Django 4.1.4 on 2023-06-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_merge_20230603_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='task_received',
            field=models.BooleanField(default=False, verbose_name='Получил задачу'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=17, verbose_name='Номер телефона'),
        ),
    ]
