# Generated by Django 4.1.4 on 2023-06-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_alter_telegramuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='order_id',
        ),
    ]
