# Generated by Django 4.1.4 on 2023-05-30 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='task',
            name='amount_of_message',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Name', max_length=150, verbose_name='Название задачи'),
            preserve_default=False,
        ),
    ]
