# Generated by Django 4.1.4 on 2023-05-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_survey', '0002_alter_questionnaire_options_task_amount_of_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный тест'),
        ),
    ]
