# Generated by Django 4.1.4 on 2023-05-30 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_survey', '0003_alter_questionnaire_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount_of_message',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
