# Generated by Django 4.1.4 on 2023-05-30 22:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_survey', '0004_alter_task_amount_of_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='eighth_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_eighth_task', to='psycho_survey.task', verbose_name='Восьмая задача'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='fifth_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_fifth_task', to='psycho_survey.task', verbose_name='Пятая задача'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='fourth_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_fourth_task', to='psycho_survey.task', verbose_name='Четвертая задача'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nineth_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_nineth_task', to='psycho_survey.task', verbose_name='Девятая задача'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='second_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_second_task', to='psycho_survey.task', verbose_name='Вторая задача'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='seventh_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_seventh_task', to='psycho_survey.task', verbose_name='Седьмая задача'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='sixth_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_sixth_task', to='psycho_survey.task', verbose_name='Шестая задача'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='tenth_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_tenth_task', to='psycho_survey.task', verbose_name='Десятая задача'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='third_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_third_task', to='psycho_survey.task', verbose_name='Третья задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='first_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_first_task', to='psycho_survey.task', verbose_name='Первая задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Активный тест'),
        ),
        migrations.AlterField(
            model_name='task',
            name='amount_of_message',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение равно 1.')]),
        ),
    ]
