# Generated by Django 4.1.4 on 2023-05-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_survey', '0005_questionnaire_eighth_task_questionnaire_fifth_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='eighth_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_eighth_task', to='psycho_survey.task', verbose_name='Восьмая задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='fifth_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_fifth_task', to='psycho_survey.task', verbose_name='Пятая задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='first_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_first_task', to='psycho_survey.task', verbose_name='Первая задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='fourth_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_fourth_task', to='psycho_survey.task', verbose_name='Четвертая задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный тест'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nineth_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_nineth_task', to='psycho_survey.task', verbose_name='Девятая задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='second_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_second_task', to='psycho_survey.task', verbose_name='Вторая задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='seventh_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_seventh_task', to='psycho_survey.task', verbose_name='Седьмая задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='sixth_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_sixth_task', to='psycho_survey.task', verbose_name='Шестая задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='tenth_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_tenth_task', to='psycho_survey.task', verbose_name='Десятая задача'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='third_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_third_task', to='psycho_survey.task', verbose_name='Третья задача'),
        ),
    ]
