# Generated by Django 4.1.4 on 2023-06-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_survey', '0010_alter_questionnaire_eighth_task_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_is_active'),
        ),
    ]
